package smartauditorium;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class registration extends javax.swing.JFrame {

    /**
     * Creates new form registration
     */
    public registration() {
        initComponents();
        this.setBounds(100,50,1120,700);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField6 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        Cancle = new javax.swing.JButton();
        repassword = new javax.swing.JTextField();
        emailaddress = new javax.swing.JTextField();
        Password = new javax.swing.JTextField();
        signup2 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("User name:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(36, 37, 143, 43);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Email Address:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(36, 98, 186, 52);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Password:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(36, 188, 178, 42);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Retype Password:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(36, 284, 215, 29);
        jPanel1.add(username);
        username.setBounds(301, 30, 522, 50);

        Cancle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Cancle.setForeground(new java.awt.Color(0, 0, 153));
        Cancle.setText("Cancle");
        Cancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancleActionPerformed(evt);
            }
        });
        jPanel1.add(Cancle);
        Cancle.setBounds(210, 400, 182, 53);
        jPanel1.add(repassword);
        repassword.setBounds(301, 278, 522, 50);
        jPanel1.add(emailaddress);
        emailaddress.setBounds(301, 104, 522, 50);
        jPanel1.add(Password);
        Password.setBounds(301, 189, 522, 50);

        signup2.setBackground(new java.awt.Color(255, 255, 255));
        signup2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        signup2.setForeground(new java.awt.Color(0, 0, 153));
        signup2.setText("Sign up now");
        signup2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup2ActionPerformed(evt);
            }
        });
        jPanel1.add(signup2);
        signup2.setBounds(600, 400, 197, 53);

        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(204, 0, 0));
        jRadioButton1.setText("I have accepted the term and condition");
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(300, 340, 530, 37);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(90, 171, 940, 476);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Sing up on Device ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(65, 7, 462, 94);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Create a free account on device and get started");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(65, 108, 580, 45);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancleActionPerformed
        // TODO add your handling code here:
        home obj= new home();
        obj.setVisible(true);
    }//GEN-LAST:event_CancleActionPerformed

    private void signup2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup2ActionPerformed
        // TODO add your handling code here:
          
    }//GEN-LAST:event_signup2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancle;
    private javax.swing.JTextField Password;
    private javax.swing.JTextField emailaddress;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField repassword;
    private javax.swing.JButton signup2;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
